### ISSUE TITLE
The authentication with Twitter failed, please check your API keys.

### ISSUE THREAD

**Issue by Awaces** [digininja/twofi#3]
Hi 

I just found this awesome tool that might help me creating custom word lists based on my target.
I just created a twitter developer account and edited the twofi.yml file.

However, my API key keeps getting revoked

**Comment by digininja** [comment]
If it is getting revoked then you are probably using it too much, try going
a bit easier and spreading out your requests.

**Comment by Awaces** [comment]
@digininja 
Thanks for the quick reply. 
That's weird because it's actually the first time i'm using the API key and tool itself.
I'm using the default command:
`sudo twofi -m 6 -u @KaliLinux`

**Comment by DavlRannos** [comment]
Getting this error any wisdom on it... not getting revoked just authentication with twitter failed

**Comment by digininja** [comment]
I've just tried and it is working fine for me. @Awaces, sorry for not coming back on this, I missed your reply and then forgot about it.

Looking at the command, it looks like you are running a packaged version rather than from GitHub, please both of you try that.

The app does not need root permissions, so `sudo` isn't needed.

**Comment by digininja** [comment]
I've not seen this problem before so it could be something different, where
are you seeing the error, in the Twitter interface?

**Comment by areinhar** [comment]
I get the same authentication error with the packaged version included in Kali. The error shows up on the command line.
When I tried the version from GitHub, I get a different error:
```
twofi.rb:83:in `rescue in twitter_search': uninitialized constant Twitter::Error::RequestTimeout (NameError)
Did you mean?  Twitter::Error::RequestEntityTooLarge
        from twofi.rb:81:in `twitter_search'
        from twofi.rb:200:in `block in <main>'
        from twofi.rb:199:in `each'
        from twofi.rb:199:in `<main>'
/usr/lib/ruby/vendor_ruby/twitter/rest/request.rb:97:in `fail_or_return_response_body': You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve (Twitter::Error::Forbidden)
        from /usr/lib/ruby/vendor_ruby/twitter/rest/request.rb:41:in `perform'
        from /usr/lib/ruby/vendor_ruby/twitter/search_results.rb:26:in `initialize'
        from /usr/lib/ruby/vendor_ruby/twitter/rest/search.rb:34:in `new'
        from /usr/lib/ruby/vendor_ruby/twitter/rest/search.rb:34:in `search'
        from twofi.rb:82:in `twitter_search'
        from twofi.rb:200:in `block in <main>'
        from twofi.rb:199:in `each'
        from twofi.rb:199:in `<main>'

```
I did not apply for Elevated access in the Twitter Developer Portal.

**Comment by digininja** [comment]
I don't support anything other than the latest GitHub checkout so I can't help with the Kali version.

What version of ruby and the twitter gem are you using?

**Comment by areinhar** [comment]
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux-gnu]
twitter (7.0.0)

**Comment by digininja** [comment]
I just tried to reproduce this and I've completely mangled my rvm setup so
I'll have to rebuild that.

If I've not come back on this in a couple of weeks, remind me, I will sort
it.

**Comment by DavidFrds** [comment]
same for me, i keep getting this error : 

```
The authentication with Twitter failed, please check your API keys.
If there is a bearer_token entry in your config file try removing that.
```
but my **twofi.yml** and credentials are corrects...

```
cat /etc/twofi/twofi.yml 
---
options:
  api_key: 6G...
  api_secret: m..
```

**Comment by digininja** [comment]
I think I may have just worked it out, how are you getting your access keys? This app is written using the original API which has been sunset by Twitter and so you can't create new keys for it. If you are creating the keys for the v2 API they won't work.

I've just signed up for a set of v2 dev keys and once I get them I'll work on updating the app to run with v2. I might rewrite it in Go while doing it, but will see.

**Comment by DavidFrds** [comment]
At first, i've been using API Keys and secret from my Consumer Keys where I created my Projects and Apps.

<img width="605" alt="Capture d’écran 2022-10-31 à 09 26 26" src="https://user-images.githubusercontent.com/84318185/198964288-e7475bf8-97fd-465a-8b2f-17f497a87f2a.png">

After reading your message, I thought I might be wrong so I used the Authentication Tokens : Access Token and Secret

<img width="598" alt="Capture d’écran 2022-10-31 à 09 30 35" src="https://user-images.githubusercontent.com/84318185/198965168-22fd70fe-28fa-45d0-b4e7-6f0f81f4f899.png">

I have absolutely no idea if im using the corrects credentials...

**Comment by digininja** [comment]
They look like v2 keys, to check, go here and see if they are listed.

https://apps.twitter.com/

This page lists the v1 keys which will work, anywhere else is v2 which won't.

**Comment by DavidFrds** [comment]
This link takes me to directly to > https://developer.twitter.com/en/portal/dashboard
There, I have not choice but to create a project and generate v2 keys.. this is what I've done to have the credentials mentioned previously.

**Comment by digininja** [comment]
That's the issue then, you've got v2 creds when the app needs v1.

I've applied for v2 creds so as soon as I get them I'll fix it up.

**Comment by DavidFrds** [comment]
arrg.. 
thanks for your time anyway, good luck I'll stay tuned ;)
